name: interact with Github API
on:
  pull_request:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Truncate SHA
        id: short_sha
        run: echo "sha_short=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Create issue with GitHub API
        run: |
          curl --request POST \
            --url "https://api.github.com/repos/${{ github.repository }}/issues" \
            --header "authorization: Bearer ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}" \
            --header "content-type: application/json" \
            --data '{
              "title": "Automated issue for commit: ${{ steps.short_sha.outputs.sha_short }}",
              "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ steps.short_sha.outputs.sha_short }}_."
            }' \
            --fail
